const quotes = [
    ["Believe you can and you're halfway there.", "Theodore Roosevelt"],
    ["You miss 100% of the shots you don't take.", "Wayne Gretzky"],
    ["Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"],
    ["Don't watch the clock; do what it does. Keep going.", "Sam Levenson"],
    ["The only way to do great work is to love what you do.", "Steve Jobs"],
    ["It does not matter how slowly you go as long as you do not stop.", "Confucius"],
    ["I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"],
    ["Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "Christian D. Larson"],
    ["What you get by achieving your goals is not as important as what you become by achieving your goals.", "Zig Ziglar"],
    ["Believe in the power of your dreams.", "Unknown"],
    ["Don't let yesterday take up too much of today.", "Will Rogers"],
    ["You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"],
    ["The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"],
    ["Do not wait for opportunities, create them.", "Unknown"],
    ["If you want to achieve greatness stop asking for permission.", "Unknown"],
    ["Strive not to be a success, but rather to be of value.", "Albert Einstein"],
    ["I attribute my success to this: I never gave or took any excuse.", "Florence Nightingale"],
    ["You don't have to be great to start, but you have to start to be great.", "Zig Ziglar"],
    ["The biggest adventure you can ever take is to live the life of your dreams.", "Oprah Winfrey"],
    ["If you are not willing to risk the usual, you will have to settle for the ordinary.", "Jim Rohn"],
    ["Believe you can and you're halfway there.", "Theodore Roosevelt"],
    ["The best way to predict the future is to invent it.", "Alan Kay"],
    ["Strive for progress, not perfection.", "Unknown"],
    ["Don't let yesterday take up too much of today.", "Will Rogers"],
    ["If you can dream it, you can achieve it.", "Zig Ziglar"],
    ["The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"],
    ["Happiness is not something readymade. It comes from your own actions.", "Dalai Lama"],
    ["You learn more from failure than from success. Don't let it stop you. Failure builds character.", "Unknown"],
    ["The only way to do great work is to love what you do.", "Steve Jobs"],
    ["The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"],
    ["Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.", "Chantal Sutherland"],
    ["It's not the years in your life that count. It's the life in your years.", "Abraham Lincoln"],
    ["The way to get started is to quit talking and begin doing.", "Walt Disney"],
    ["The best time to plant a tree was 20 years ago. The second best time is now", "chinese Proverb"],
    ["I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "Jimmy Dean"],
    ["Perfection is not attainable, but if we chase perfection we can catch excellence.", "Vince Lombardi"],
    ["Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "Christian D. Larson"],
    ["You miss 100% of the shots you don't take.", "Wayne Gretzky"],
    ["The only way to do great work is to love what you do.", "Steve Jobs"],
    ["Happiness is not something ready made. It comes from your own actions.", "Dalai Lama XIV"],
    ["You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"],
    ["Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"],
    ["Strive not to be a success, but rather to be of value.", "Albert Einstein"],
    ["I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"],
    ["The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"],
    ["Believe in the power of your dreams.", "Unknown"],
    ["The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"],
    ["It is during our darkest moments that we must focus to see the light.", "Aristotle Onassis"],
    ["You have within you right now, everything you need to deal with whatever the world can throw at you.", "Brian Tracy"],
    ["It does not matter how slowly you go as long as you do not stop.", "Confucius"],
    ["We may encounter many defeats but we must not be defeated.", "Maya Angelou"],
    ["The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"],
    ["If you can dream it, you can achieve it.", "Zig Ziglar"],
    ["Do not let what you cannot do interfere with what you can do.", "John Wooden"],
    ["Happiness is not the absence of problems, it's the ability to deal with them.", "Steve Maraboli"],
    ["The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"],
    ["What you get by achieving your goals is not as important as what you become by achieving your goals.", "Zig Ziglar"],
    ["Don't let yesterday take up too much of today.", "Will Rogers"],
    ["Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", "Albert Schweitzer"],
    ["The only way of finding the limits of the possible is by going beyond them into the impossible.", "Arthur C. Clarke"],
    ["The best way to predict your future is to create it.", "Abraham Lincoln"],
    ["The only source of knowledge is experience.", "Albert Einstein"],
    ["Believe you can and you're halfway there.", "Theodore Roosevelt"],
    ["Try to be a rainbow in someone's cloud.", "Maya Angelou"],
    ["You can't build a reputation on what you are going to do.", "Henry Ford"], ["The only thing we have to fear is fear itself", "Theodore Roosevelt"]]

    export default quotes;